name: 'Terraform Plan (Pull Request - Dev)'

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform-plan:
    name: 'Terraform Plan Dev'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PLAN_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (dev)
        run: terraform init -backend-config="envs/dev/backend.hcl"

      # Paso 1: Linting (formato)
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Paso 1: Validación
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (dev)
        id: plan
        run: terraform plan -no-color -var-file="envs/dev/terraform.tfvars"
        continue-on-error: true

      - name: Publicar el Plan en el PR
        uses: actions/github-script@v7
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          PLAN_OUTPUT: |
            #### Terraform Plan (dev)
            ```terraform
            ${{ steps.plan.outputs.stdout }}
            ```
        with:
          script: |
            const output = process.env.PLAN_OUTPUT;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
