
name: 'Terraform Apply (Main)'

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::695100305629:role/github-actions-apply-role # <-- key: 'apply_role_arn'
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply

        run: terraform apply -auto-approve